### ISSUE TITLE
Deploy script unused command

### ISSUE THREAD

**Issue by RRMoelker** [jbmoelker/jinja-compat-tests#6]
typo in the deploy script, the line `0` seems to do nothing:

https://github.com/jbmoelker/jinja-compat-tests/blob/master/scripts/deploy.sh#L37

**Comment by jbmoelker** [comment]
Absolutely right. Should be like this: https://github.com/voorhoede/front-end-tooling-recipes/blob/master/travis-deploy-to-gh-pages/scripts/deploy.sh
